import { ThemeProvider } from '../components/theme-provider'
import '../globals.css'

export const metadata = {
  title: 'Alvaro Peña',
  description: 'Generated by Next + Sanity',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head />
      <body>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem />
        {children}
      </body>
    </html>
  )
}
