import Header from '../components/header'
import { ThemeProvider } from '../components/theme-provider'
import '../globals.css'

export const metadata = {
  title: 'Alvaro Peña',
  description: 'Generated by Next + Sanity',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
      <body className="max-w-3xl mx-auto py-10">
        <Header />
        <ThemeProvider>
          <main className="py-20">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  )
}
